services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: das-laravel
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db       # Nombre del servicio del contenedor de postgres
      DB_PORT: 5432
      DB_DATABASE: das_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: anagvs36@gmail.com
      MAIL_PASSWORD: drhoiwwgiqboivtq
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: anagvs36@gmail.com
    depends_on:
      - db
    networks:
      - das-net
  nginx:
    image: nginx:latest
    container_name: das
    expose:
      - "80"
    # ports:
    #   - "8080:80" #---> despliegue local con puerto 8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - das-net
      - internal-network
      - proxy-network
  db:
    image: postgres:latest
    container_name: das-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: das_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - das-net

networks:
  das-net:
    driver: bridge
  internal-network:
    external: true
  proxy-network:
    external: true

volumes:
  db-data: