services:
  postgres:
    image: postgres:16
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vesperatim
      TZ: "America/La_Paz"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - laravel-net
    env_file:
      - .env.docker

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8000"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel_db
      DB_USERNAME: postgres
      DB_PASSWORD: vesperatim
      APP_KEY:
    volumes:
      - .:/var/www
    networks:
      - laravel-net
    env_file:
      - .env.docker

volumes:
  db_data:

networks:
  laravel-net:
